// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY2gW5ISv9uFqqCIlPJ94TBUYdNcYuDcM',
    appId: '1:929171017075:web:0fc3fcf96538869d444906',
    messagingSenderId: '929171017075',
    projectId: 'courseverse-c9955',
    authDomain: 'courseverse-c9955.firebaseapp.com',
    storageBucket: 'courseverse-c9955.firebasestorage.app',
    measurementId: 'G-VEZ8RVBPXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuIR4xDbAj_kLzlbrlKdPOHzMBM9IDi2c',
    appId: '1:929171017075:android:885c4c3f7d870b45444906',
    messagingSenderId: '929171017075',
    projectId: 'courseverse-c9955',
    storageBucket: 'courseverse-c9955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-VrzP9EiacaR1DtW2TG8miI6dSJ-Lwd8',
    appId: '1:929171017075:ios:93e001fa41d59d70444906',
    messagingSenderId: '929171017075',
    projectId: 'courseverse-c9955',
    storageBucket: 'courseverse-c9955.firebasestorage.app',
    iosClientId: '929171017075-58lignv779nqjtk2uv1nhskc28elh47n.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY2gW5ISv9uFqqCIlPJ94TBUYdNcYuDcM',
    appId: '1:929171017075:web:49e0dcd3e79e64f8444906',
    messagingSenderId: '929171017075',
    projectId: 'courseverse-c9955',
    authDomain: 'courseverse-c9955.firebaseapp.com',
    storageBucket: 'courseverse-c9955.firebasestorage.app',
    measurementId: 'G-4CLWZCS43X',
  );
}
